 /**
         * 实现二级菜单级联
         */
  var provinces=[
    {
        id:1001,
        name:'江苏省',
        schools:[
            {
                id:1,
                name:'南京大学'
            },
            {
                id:2,
                name:'苏州大学'
            },
            {
                id:3,
                name:'扬州大学'
            },
            {
                id:4,
                name:'徐州矿业大学'
            },
            {
                id:5,
                name:'上海海事大学'
            },
            {
                id:6,
                name:'上海大学'
            },
            {
                id:7,
                name:'上海职业技术学院'
            }
        ]
    },
    {
        id:1002,
        name:'山东省',
        schools:[
            {
                id:1,
                name:'济南大学'
            },
            {
                id:2,
                name:'青岛大学'
            },
            {
                id:3,
                name:'威海职业技术学院'
            },
            {
                id:4,
                name:'烟台大学'
            },
            {
                id:5,
                name:'鲁东大学'
            }
            ,
            {
                id:6,
                name:'山东大学'
            }
            ,
            {
                id:7,
                name:'齐鲁工业大学'
            }
        ]
    },
    {
        id:1003,
        name:'福建省',
        schools:[
            {
                id:1,
                name:'福州大学'
            },
            {
                id:2,
                name:'厦门大学'
            },
            {
                id:3,
                name:'福建师范大学'
            },
            {
                id:4,
                name:'福建技术大学'
            },
            {
                id:5,
                name:'福建水产养殖大学'
            },
            {
                id:6,
                name:'福州职业技术学院'
            },
            {
                id:7,
                name:'华侨大学'
            }
        ]
    },
    {
        id:1004,
        name:'河北省',
        schools:[
            {
                id:1,
                name:'河北工业大学'
            },
            {
                id:2,
                name:'河北大学'
            },
            {
                id:3,
                name:'河北职业技术学院'
            },
            {
                id:4,
                name:'河北农业大学'
            },
            {
                id:5,
                name:'石家庄铁道大学'
            }
            ,
            {
                id:6,
                name:'河北建筑大学'
            }
            ,
            {
                id:7,
                name:'河北工业大学'
            }
        ]
    },
    {
        id:1005,
        name:'广东省',
        schools:[
            {
                id:1,
                name:'广州大学'
            },
            {
                id:2,
                name:'中山大学'
            },
            {
                id:3,
                name:'华南理工大学'
            },
            {
                id:4,
                name:'佛山大学'
            },
            {
                id:5,
                name:'深圳大学'
            }
        ]
    }
];
window.onload = function(){
    var province = document.getElementById("province");
    var school = document.getElementById("school");
    province.onchange = function(){
        // 清除之前school下拉框内的数据,只留下第一个option
        if(school.length>1){
            school.length = 1;
        }
        var selected = provinces[province.selectedIndex-1]; //被选中省份的JSON对象
        for(var i=0;i<selected.schools.length;i++){
            //学校的name作为文本，学校的id作为value,创建新的option对象
            var option = new Option(selected.schools[i].name,selected.schools[i].id); 
            school.add(option);//将option对象添加到school的末尾
        }
        // school.selectedIndex = 1; //默认显示第二个option，即省会城市                      
    }
}
